### ISSUE TITLE
'FastRCNNFocalLoss' object has no attribute 'box_reg_loss'

### ISSUE THREAD

**Issue by 2thedarkside** [HunterJ-Lin/ActiveTeacher#2]
## Error Message
/home/.../anaconda3/envs/detectron2/lib/python3.7/site-packages/torch/_tensor.py:575: UserWarning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (Triggered internally at  /opt/conda/conda-bld/pytorch_1631630742027/work/aten/src/ATen/native/BinaryOps.cpp:467.)
  return torch.floor_divide(self, other)
Exception during training:
Traceback (most recent call last):
  File "/home/.../task/ActiveTeacher/activeteacher/engine/trainer.py", line 167, in train_loop
    self.run_step_full_semisup()
  File "/home/.../task/ActiveTeacher/activeteacher/engine/trainer.py", line 266, in run_step_full_semisup
    label_data_q, branch="supervised")
  File "/home/.../anaconda3/envs/detectron2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/.../task/ActiveTeacher/activeteacher/modeling/meta_arch/rcnn.py", line 32, in forward
    images, features, proposals_rpn, gt_instances, branch=branch
  File "/home/.../anaconda3/envs/detectron2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/.../task/ActiveTeacher/activeteacher/modeling/roi_heads/roi_heads.py", line 96, in forward
    features, proposals, compute_loss, compute_val_loss, branch
  File "/home/.../task/ActiveTeacher/activeteacher/modeling/roi_heads/roi_heads.py", line 123, in _forward_box
    losses = self.box_predictor.losses(predictions, proposals)
  File "/home/.../task/ActiveTeacher/activeteacher/modeling/roi_heads/fast_rcnn.py", line 108, in losses
    num_classes=self.num_classes,
  File "/home/.../task/ActiveTeacher/activeteacher/modeling/roi_heads/fast_rcnn.py", line 143, in losses
    "loss_box_reg": self.box_reg_loss(),
AttributeError: 'FastRCNNFocalLoss' object has no attribute 'box_reg_loss'

## Environment
- python=3.7
- CUDA=10.2
- PyTorch=1.9.1
- torchvision=0.10.1
- detectron2=0.6+cu102 (tried v0.5 but also failed)

## Possible Problem
The FastRCNNOutputs class you refactored [here](https://github.com/HunterJ-Lin/ActiveTeacher/blob/main/activeteacher/modeling/roi_heads/fast_rcnn.py#L143) has no `box_reg_loss` implementation.

Could you help with it? Many thanks!

**Comment by HunterJ-Lin** [comment]
I have fixed this file, thanks for the feedback.

**Comment by 2thedarkside** [comment]
It worked. Thanks for your quick reply.

Besides, could you provide config files for the VOC dataset to reproduce your results? Thanks in advance :)

**Comment by HunterJ-Lin** [comment]
> 

Hi, we have released our VOC07+VOC12 configs. NOTICE THAT PLEASE!!! WE DID NOT FINE TUNE THIS.
